include: package:flutter_lints/flutter.yaml

linter:
  rules:
  - cancel_subscriptions
  - prefer_single_quotes
  - directives_ordering
  - avoid_void_async
  - unawaited_futures
  - prefer_relative_imports
  - sort_constructors_first
  - sort_unnamed_constructors_first
  - prefer_const_constructors
  - prefer_const_declarations
  - prefer_final_locals
  - require_trailing_commas

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
    invalid_annotation_target: ignore
  exclude:
  - "**.g.dart"
  - "**.mocks.dart"
